### ISSUE TITLE
The plugin has very poor install for Linux.

### ISSUE THREAD

**Issue by swaminathanpr** [andricDu/vscode-jq#2]
The plugin has very poor install for Linux. The file type of the installed jq is not even that of linux.
doing a file on jq that got installed shows this
jq: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>

The workaround is to install jq and then create a symlink to the installed jq in the 
~/.vscode/extensions/dandric.vscode-jq-0.0.17/out/bin
directory.

**Comment by andricDu** [comment]
Thanks for letting me know, I'll spin up a VM and take a look.

**Comment by andricDu** [comment]
Turns out I accidentally published extension with a binary included. I've verified that plugin v0.0.18 works in Ubuntu 16.04.

**Comment by swaminathanpr** [comment]
That was pretty fast! Thanks for the super quick fix!
