### ISSUE TITLE
Put output into new editor window - split window

### ISSUE THREAD

**Issue by andricDu** [andricDu/vscode-jq#6]
## Feature

The current output pane I believe truncates output after a certain number of lines. It might be more useful for users if the output could be put into a split window for saving or for further analysis into potentially another window and so on.

**Comment by vk4779** [comment]
Please check https://github.com/andricDu/vscode-jq/pull/7 
This is a fix for output truncation.

**Comment by andricDu** [comment]
Thanks @vk4779, I'll take a look!

**Comment by andricDu** [comment]
closing this one as the truncation is fixed. Will consider opening new issue for the option of splitting the output to a new tab. 

Thanks @vk4779
