### ISSUE TITLE
cannot execute binary file error

### ISSUE THREAD

**Issue by TryTryAgain** [andricDu/vscode-jq#8]
On MacOS 10.14.6, using the latest 0.0.18 version of vscode-jq and the latest 1.40.2 version of vscode.

Upon exectuting the jq statement I get the following error:
`/Users/myusername/.vscode/extensions/dandric.vscode-jq-1.1.0/out/bin/jq: /Users/myusername/.vscode/extensions/dandric.vscode-jq-1.1.0/out/bin/jq: cannot execute binary file`

If I stat the file, it looks like this:
`16777220 12968865027 -rwxr-xr-x 1 myusername staff 0 3027945 "Dec 12 13:50:01 2019" "Dec 12 13:47:55 2019" "Dec 12 13:47:55 2019" "Dec 12 13:47:55 2019" 4096 5920 0 /Users/myusername/.vscode/extensions/dandric.vscode-jq-1.1.0/out/bin/jq`

**Comment by andricDu** [comment]
Thanks for reporting this @TryTryAgain 

Just to help the investigation, can you download jq from https://stedolan.github.io/jq/ and run that successfully without error?

**Comment by TryTryAgain** [comment]
I am running `jq`, from a homebrew install though... 
```
└─ $ ▶ which jq
/usr/local/bin/jq
```

Anyway, downloading from https://stedolan.github.io/jq/ and running `cat some.json | ./jq-osx-amd64 '.'` as a simple test works without error and as expected.

**Comment by libinvarghese** [comment]
I am also experiencing the same on my Mac 10.13.6! On further investigation I found that the binary downloaded is that of linux instead of osx

```
 ~/./e/dandric.vscode-jq-1.1.0  pwd
/Users/xxxx/.vscode/extensions/dandric.vscode-jq-1.1.0
 ~/./e/dandric.vscode-jq-1.1.0  md5 out/bin/jq
MD5 (out/bin/jq) = 6a342dbb17b2f2ea4ec0e64d2157614d
 ~/./e/dandric.vscode-jq-1.1.0  md5 ~/Downloads/jq-linux64
MD5 (/Users/xxxx/Downloads/jq-linux64) = 6a342dbb17b2f2ea4ec0e64d2157614d
 ~/./e/dandric.vscode-jq-1.1.0  md5 ~/Downloads/jq-osx-amd64
MD5 (/Users/xxxx/Downloads/jq-osx-amd64) = 81ff0e3ddd999d2f5bd151b882ce7e18
```

**Comment by andricDu** [comment]
Oh wow that is no good, thanks for investigating. I'll have a fix for this shortly.

**Comment by andricDu** [comment]
you can give it a try now.

**Comment by andricDu** [comment]
Closing. Let me know if issue persists.

**Comment by TryTryAgain** [comment]
All good now, appreciate it!
